version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dynamodb-clone"
s3_prefix = "dynamodb-clone"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
